## Switches
set_property PACKAGE_PIN V17 [get_ports {address(0)}]
	set_property IOSTANDARD LVCMOS33 [get_ports {address(0)}]
set_property PACKAGE_PIN V16 [get_ports {address(1)}]
	set_property IOSTANDARD LVCMOS33 [get_ports {address(1)}]
set_property PACKAGE_PIN W16 [get_ports {address(2)}]
	set_property IOSTANDARD LVCMOS33 [get_ports {address(2)}]
set_property PACKAGE_PIN W17 [get_ports {address(3)}]
	set_property IOSTANDARD LVCMOS33 [get_ports {address(3)}]

## LEDs
set_property PACKAGE_PIN U16 [get_ports {data(0)}]
	set_property IOSTANDARD LVCMOS33 [get_ports {data(0)}]
set_property PACKAGE_PIN E19 [get_ports {data(1)}]
	set_property IOSTANDARD LVCMOS33 [get_ports {data(1)}]
set_property PACKAGE_PIN U19 [get_ports {data(2)}]
	set_property IOSTANDARD LVCMOS33 [get_ports {data(2)}]
set_property PACKAGE_PIN V19 [get_ports {data(3)}]
	set_property IOSTANDARD LVCMOS33 [get_ports {data(3)}]
set_property PACKAGE_PIN W18 [get_ports {data(4)}]
	set_property IOSTANDARD LVCMOS33 [get_ports {data(4)}]
set_property PACKAGE_PIN U15 [get_ports {data(5)}]
	set_property IOSTANDARD LVCMOS33 [get_ports {data(5)}]
set_property PACKAGE_PIN U14 [get_ports {data(6)}]
	set_property IOSTANDARD LVCMOS33 [get_ports {data(6)}]
